### ISSUE TITLE
Slack broken

### ISSUE THREAD

**Issue by khrj** [sampoder/sampoder#2]
Does slack work for you?

**Comment by marius-schaefer** [comment]
not really, is this how we will communicate

**Comment by khrj** [comment]
I guess so

**Comment by marius-schaefer** [comment]
should we create a discoed?

**Comment by khrj** [comment]
Yeah, https://discord.gg/xkNguw4T

**Comment by rishiosaur** [comment]
anyone have instagram? I can add y'all to the big hack club gc

**Comment by khrj** [comment]
What's "gc"?

**Comment by marius-schaefer** [comment]
group chat
and yes rishi, marius._.schaefer

**Comment by sampoder** [comment]
Slack is back!

**Comment by marius-schaefer** [comment]
not really

**Comment by khrj** [comment]
slack kinda back

**Comment by khrj** [comment]
but.... not too back
